# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-04 15:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Foto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fotoUrl', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=32)),
                ('cuerpo', models.CharField(max_length=300)),
                ('autor', models.CharField(max_length=32)),
                ('precio', models.FloatField()),
                ('editorial', models.CharField(max_length=32)),
                ('fechaPublicacion', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='LibroUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='genEden.Libro')),
            ],
        ),
        migrations.CreateModel(
            name='LogsHumedad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now=True)),
                ('valor', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='LogsLuminosidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now=True)),
                ('valor', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='LogsNivel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now=True)),
                ('valor', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='LogsTemperatura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now=True)),
                ('valor', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='LogsValvula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now=True)),
                ('valor', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Maceta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaPlantacion', models.DateTimeField(null=True)),
                ('primeraCosecha', models.DateTimeField(null=True)),
                ('serial', models.CharField(max_length=32, null=True, unique=True)),
                ('experiencia', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Planta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passw', models.CharField(max_length=32)),
                ('nombre', models.CharField(max_length=32)),
                ('email', models.CharField(max_length=32)),
                ('pais', models.CharField(max_length=32, null=True)),
                ('ciudad', models.CharField(max_length=32, null=True)),
                ('fechaNacimiento', models.DateField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='maceta',
            name='tipoPlanta',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='macetas_planta', to='genEden.Planta'),
        ),
        migrations.AddField(
            model_name='maceta',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='macetas', to='genEden.User'),
        ),
        migrations.AddField(
            model_name='logsvalvula',
            name='maceta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valvula', to='genEden.Maceta'),
        ),
        migrations.AddField(
            model_name='logstemperatura',
            name='maceta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temperatura', to='genEden.Maceta'),
        ),
        migrations.AddField(
            model_name='logsnivel',
            name='maceta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nivel', to='genEden.Maceta'),
        ),
        migrations.AddField(
            model_name='logsluminosidad',
            name='maceta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='luminosidad', to='genEden.Maceta'),
        ),
        migrations.AddField(
            model_name='logshumedad',
            name='maceta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='humedad', to='genEden.Maceta'),
        ),
        migrations.AddField(
            model_name='librouser',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='genEden.User'),
        ),
        migrations.AddField(
            model_name='foto',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='genEden.User'),
        ),
    ]
